### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory in hierarchy project

### ISSUE THREAD

**Issue by tongilcoto** [ivangsa/karate-ide#10]
I am getting a NoClassDefFoundError: org/slf4j/LoggerFactory exception in a hierarchy project although class path seems to be well formed.
This is the error

```
Executing: java '-Dkarate.env=' '-Dvscode.port=62986' -cp '/Users/XXXXX/.vscode/extensions/karateide.karate-ide-0.9.5/resources/vscode.jar:src/test/java:src/test/resources:target/classes:target/test-classes:/Users/XXXXX/.m2/repository/com/intuit/karate/karate-core/1.1.0/karate-core-1.1.0.jar;/Users/XXXXX/.m2/repository/org/graalvm/js/js-scriptengine/21.2.0/js-scriptengine-21.2.0.jar;/Users/XXXXX/.m2/repository/org/graalvm/sdk/graal-sdk/21.2.0/graal-sdk-21.2.0.jar;/Users/XXXXX/.m2/repository/org/graalvm/js/js/21.2.0/js-21.2.0.jar;/Users/XXXXX/.m2/repository/org/graalvm/regex/regex/21.2.0/regex-21.2.0.jar;/Users/XXXXX/.m2/repository/org/graalvm/truffle/truffle-api/21.2.0/truffle-api-21.2.0.jar;/Users/XXXXX/.m2/repository/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar;/Users/XXXXX/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar;/Users/XXXXX/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar;/Users/XXXXX/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar;/Users/XXXXX/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar;/Users/XXXXX/.m2/repository/com/jayway/jsonpath/json-path/2.6.0/json-path-2.6.0.jar;/Users/XXXXX/.m2/repository/net/minidev/json-smart/2.4.7/json-smart-2.4.7.jar;/Users/XXXXX/.m2/repository/net/minidev/accessors-smart/2.4.7/accessors-smart-2.4.7.jar;/Users/XXXXX/.m2/repository/org/ow2/asm/asm/9.1/asm-9.1.jar;/Users/XXXXX/.m2/repository/info/cukes/cucumber-java/1.2.5/cucumber-java-1.2.5.jar;/Users/XXXXX/.m2/repository/info/cukes/cucumber-core/1.2.5/cucumber-core-1.2.5.jar;/Users/XXXXX/.m2/repository/org/yaml/snakeyaml/1.29/snakeyaml-1.29.jar;/Users/XXXXX/.m2/repository/de/siegmar/fastcsv/2.0.0/fastcsv-2.0.0.jar;/Users/XXXXX/.m2/repository/info/picocli/picocli/4.6.1/picocli-4.6.1.jar' vscode.KarateTestProcess --backup-reportdir=false -H vscode.VSCodeHook  'src/test/java/entityData/entity/getEntity/get-entity.feature:27'

Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at vscode.KarateTestProcess.<clinit>(KarateTestProcess.java:21)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        NOTE: If you're seeing this message your "karateIDE.karateCli.classpath" setting is probably misconfigured.
        Please refer to the documentation for more information https://github.com/ivangsa/karate-ide#karate-classpath
        And run the "Configure Karate-IDE karate classpath" command for assistance (View > Command Palette or Ctrl+Shift+P).
        You can also consider installing "KarateIDE Classpath Jar" extension so you don't need to download karate.jar
        and stay up to date with the latest and greatest Karate release (coming soon).
                    
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

The project has no direct karate dependency, which are got from a parent project

This is parent's pom.xml, which includes karate-junit4 and karate-junit5 with karate 1.1.0 and karate-apache 0.9.4 (there's no karate-apache 1.1.0 yet ... https://repo1.maven.org/maven2/com/intuit/karate/karate-apache/ ) I also had to add a dependencyManagement section in order to handle conflicts

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>XXXXXXX</groupId>
    <artifactId>XXXXXX</artifactId>
    <version>1.0.0</version>
  </parent>

  <groupId>YYYYYYYYYY</groupId>
  <artifactId>YYYYYYYYY</artifactId>
  <version>1.4.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <java.version>1.8</java.version>
    <maven.compiler.version>3.6.0</maven.compiler.version>
    <maven.jar-plugin.version>3.1.2</maven.jar-plugin.version>
    <karate.version>1.1.0</karate.version>
    <gatling.plugin.version>2.2.4</gatling.plugin.version>
    <maven.surefire.version>3.0.0-M3</maven.surefire.version>
    <!-- ZZZZZZZ-versions -->
    <ZZZZZZZZZZ..version>1.2.4-SNAPSHOT</ZZZZZZZ.version>
    <ZZZZZZZZZZZ..version>1.9.3-SNAPSHOT</ZZZZZZZZZZZ.version>
    <jacoco.version>0.8.4</jacoco.version>
  </properties>

  <dependencies>


    <dependency>
      <groupId>com.intuit.karate</groupId>
      <artifactId>karate-junit4</artifactId>
      <version>${karate.version}</version>
    </dependency>

    <dependency>
      <groupId>com.intuit.karate</groupId>
      <artifactId>karate-junit5</artifactId>
      <version>${karate.version}</version>
    </dependency>

    <dependency>
      <groupId>com.intuit.karate</groupId>
      <artifactId>karate-apache</artifactId>
      <version>0.9.4</version>
    </dependency>

    <dependency>
      <groupId>net.masterthought</groupId>
      <artifactId>cucumber-reporting</artifactId>
      <version>3.8.0</version>
    </dependency>

    <dependency>
      <groupId>com.googlecode.json-simple</groupId>
      <artifactId>json-simple</artifactId>
      <version>1.1.1</version>
    </dependency>

  </dependencies>

  <build>

    <plugins>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven.compiler.version}</version>
        <configuration>
          <encoding>UTF-8</encoding>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <compilerArgument>-Werror</compilerArgument>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>${jacoco.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report</id>
            <phase>test</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

    </plugins>
    
  </build>

  <dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.1</version>
        </dependency>
        <dependency>
            <groupId>com.intuit.karate</groupId>
            <artifactId>karate-core</artifactId>
            <version>1.1.0</version>
        </dependency>
    </dependencies>
</dependencyManagement>

</project>
```

These are the dependencies for both projects as shown by VS Code 

![Captura de pantalla 2021-11-29 a las 10 05 32](https://user-images.githubusercontent.com/28577702/143841516-57f2b5d9-775a-4765-b824-4697d3150fd1.png)

When using VS Code Configure Karate-IDE karate classpath from Command Palette and selecting M2_REPO option, in the parent project I got this new setting
```
 "karateIDE.karateCli.classpath": "src/test/java:src/test/resources:target/classes:target/test-classes:${m2.repo}/com/intuit/karate/karate-core/1.1.0/karate-core-1.1.0.jar;${m2.repo}/org/graalvm/js/js-scriptengine/21.2.0/js-scriptengine-21.2.0.jar;${m2.repo}/org/graalvm/sdk/graal-sdk/21.2.0/graal-sdk-21.2.0.jar;${m2.repo}/org/graalvm/js/js/21.2.0/js-21.2.0.jar;${m2.repo}/org/graalvm/regex/regex/21.2.0/regex-21.2.0.jar;${m2.repo}/org/graalvm/truffle/truffle-api/21.2.0/truffle-api-21.2.0.jar;${m2.repo}/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar;${m2.repo}/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar;${m2.repo}/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar;${m2.repo}/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar;${m2.repo}/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar;${m2.repo}/com/jayway/jsonpath/json-path/2.6.0/json-path-2.6.0.jar;${m2.repo}/net/minidev/json-smart/2.4.7/json-smart-2.4.7.jar;${m2.repo}/net/minidev/accessors-smart/2.4.7/accessors-smart-2.4.7.jar;${m2.repo}/org/ow2/asm/asm/9.1/asm-9.1.jar;${m2.repo}/info/cukes/cucumber-java/1.2.5/cucumber-java-1.2.5.jar;${m2.repo}/info/cukes/cucumber-core/1.2.5/cucumber-core-1.2.5.jar;${m2.repo}/org/yaml/snakeyaml/1.29/snakeyaml-1.29.jar;${m2.repo}/de/siegmar/fastcsv/2.0.0/fastcsv-2.0.0.jar;${m2.repo}/info/picocli/picocli/4.6.1/picocli-4.6.1.jar",
```

but when I use the same option in my project, there is no new karateIDE.karateCli.classpath option at settings.json. In any case, the classpath is generated as I pasted the run test command logs in the beginning of this issue

**Comment by ivangsa** [comment]
hi @tongilcoto 

all the pom information is not relevant for KarateIDE extension to run your tests...

I detected an error in your "karateIDE.karateCli.classpath" setting (which is the only relevant in this case)

It is mixing ":" and ";" as path separator... If you are on linux/mac this is a bug in "Classpath configuration wizard" and we will fix it shortly

You can fix your setting by replacing: ";" with ":"

```
"karateIDE.karateCli.classpath": "src/test/java:src/test/resources:target/classes:target/test-classes:${m2.repo}/com/intuit/karate/karate-core/1.1.0/karate-core-1.1.0.jar:${m2.repo}/org/graalvm/js/js-scriptengine/21.2.0/js-scriptengine-21.2.0.jar:${m2.repo}/org/graalvm/sdk/graal-sdk/21.2.0/graal-sdk-21.2.0.jar:${m2.repo}/org/graalvm/js/js/21.2.0/js-21.2.0.jar:${m2.repo}/org/graalvm/regex/regex/21.2.0/regex-21.2.0.jar:${m2.repo}/org/graalvm/truffle/truffle-api/21.2.0/truffle-api-21.2.0.jar:${m2.repo}/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar:${m2.repo}/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:${m2.repo}/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:${m2.repo}/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:${m2.repo}/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar:${m2.repo}/com/jayway/jsonpath/json-path/2.6.0/json-path-2.6.0.jar:${m2.repo}/net/minidev/json-smart/2.4.7/json-smart-2.4.7.jar:${m2.repo}/net/minidev/accessors-smart/2.4.7/accessors-smart-2.4.7.jar:${m2.repo}/org/ow2/asm/asm/9.1/asm-9.1.jar:${m2.repo}/info/cukes/cucumber-java/1.2.5/cucumber-java-1.2.5.jar:${m2.repo}/info/cukes/cucumber-core/1.2.5/cucumber-core-1.2.5.jar:${m2.repo}/org/yaml/snakeyaml/1.29/snakeyaml-1.29.jar:${m2.repo}/de/siegmar/fastcsv/2.0.0/fastcsv-2.0.0.jar:${m2.repo}/info/picocli/picocli/4.6.1/picocli-4.6.1.jar",
```

Please confirm it works for you and thanks for reporting this.

**Comment by tongilcoto** [comment]
mmmm, thanks @ivangsa, yes, I am using Mac ...
That karate-ide classpath I shared was for the parent , as I said when generating classpath for the project VS Code didn't add anything ...
So, as a workaround I just added it manually with the substitution (using the logs java classpath)  .... and it worked!!!

**Comment by tongilcoto** [comment]
Now I am getting errors at java files when importing com.intuit.karate ...

![Captura de pantalla 2021-11-29 a las 13 31 52](https://user-images.githubusercontent.com/28577702/143869902-094e6802-db34-48a1-babc-d73bd1142da4.png)

Could it be a side effect of this issue with ';' and ':'? (I've solved karate classpath but java classpath still uses ';')

**Comment by ivangsa** [comment]
Not related to "karateIDE.karateCli.classpath"
"karateIDE.karateCli.classpath" only affects KarateIDE command line..
