### ISSUE TITLE
KarateIDE not able to start karate test - TypeError: Cannot read properties of undefined (reading 'parent')

### ISSUE THREAD

**Issue by gba-foundever** [ivangsa/karate-ide#35]
Using last vscode 1.95.1 and KarateIDE v1.5.0 + Karate IDE Classpath Jar v1.4.0

On two og-f my project I'm not able to use the plugin, I got following error. On other it work well, project are a little bit differents but very close:
- both using last gradle wrapper 8.10.2
- both having a karate-config.js on root of the project
- main difference is that one as tests in `src/e2e-test/resources/karate` (the not working one) and other in `src/system-test/resources/karate` (working one)

```
2024-11-04 12:57:47.293 [error] TypeError: Cannot read properties of undefined (reading 'parent')
    at si.fromExtHostTestItem (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:554)
    at file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:76653
    at Array.map (<anonymous>)
    at UM.createTestRun (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:76643)
    at Object.createTestRun (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:67174)
    at x (/Users/username/.vscode/extensions/karateide.karate-ide-1.5.0/dist/extension.js:2:235785)
    at h (/Users/username/.vscode/extensions/karateide.karate-ide-1.5.0/dist/extension.js:2:233407)
    at t.relaunchTest (/Users/username/.vscode/extensions/karateide.karate-ide-1.5.0/dist/extension.js:2:233893)
    at /Users/username/.vscode/extensions/karateide.karate-ide-1.5.0/dist/extension.js:2:289785
    at Y0.h (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32833)
    at Y0.$executeContributedCommand (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:33683)
    at py.S (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)
    at py.Q (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)
    at py.M (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)
    at py.L (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111285)
    at mh.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)
    at D.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at mh.value (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13279)
    at D.B (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at MessagePortMain.<anonymous> (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11571)
    at MessagePortMain.emit (node:events:519:28)
    at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949) karateIDE.karateExecutionsTree.runLastExecution {"value":"KarateIDE.karate-ide","_lower":"karateide.karate-ide"}
```

**Comment by gba-foundever** [comment]
Additional info:

Error is seeable in logs of extension host

In Karate IDE › Tests: Glob Filter, I got `**/src/system-test/**/*.feature`

If I change it to `**/src/e2e-test/**/*.feature` -> both type of project are not working with error above
If I come back to `**/src/system-test/**/*.feature`, the one with system-test work again

In addition I all case I got also this error in logs, but may be not linked

```
2024-11-04 14:21:00.331 [error] Error: command failed with error code 2: error parsing glob '**/${ext/**/*.{feature,yml,json}': nested alternate groups are not allowed

    at y_i (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:537:7354)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3124:9591
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3124:7904
```

**Comment by ivangsa** [comment]
Hi @gba-foundever 

I guess there is something strange regarding filenames in the project that doesnt work

Can you send me the list of filenames in `e2e-test` to ivangsa at gmail.com

(you can get the list name with `find src/e2e-test`)

**Comment by gba-foundever** [comment]
Hi,
I can do better @ivangsa 
Please find 2 small projects : exactly same content, only difference is the test base folder name
[not-working.zip](https://github.com/user-attachments/files/17623468/not-working.zip)
[working.zip](https://github.com/user-attachments/files/17623471/working.zip)

regards

**Comment by ivangsa** [comment]
Hi @gba-foundever 

I tested this in windows and linux and it worked for me..

![image](https://github.com/user-attachments/assets/d2233841-85ee-4157-ba74-c6457992b839)

Does this minimal project fail on MacOX for you?

**Comment by gba-foundever** [comment]
Yes exactly on macos
When I hit the Karate in the bottom bar (but I don't have the run button on the .feature file also)

![image](https://github.com/user-attachments/assets/d1012df2-1ead-407a-ab14-d23c72af54ec)

**Comment by gba-foundever** [comment]
May be another input
on the working one, if I press on Karate at the bottom at start I got the same issue, but after I run a feature its ok 
![image](https://github.com/user-attachments/assets/85d2a663-5080-4489-933e-e438d9080dac)

**Comment by gba-foundever** [comment]
Finally I got it !
It's 2 differents problems that made me confuse

The run button is present based on your settings, if I adjust it it works like a charm
![image](https://github.com/user-attachments/assets/863d6131-39bb-4152-8066-f4326293b96e)

If I put `**/src/*-test/**/*.feature` iniside it's working perfectly

The issue of `Cannot read...` occurs if you hit the karate button in the below bar without having launched any karate test. Once you launch a test, after you can click with trouble
So just an issue with initial state of the karate button
 
 
 And may be a second issue with following error. I don't see where '**/${ext/**/*.{feature,yml,json}' is defined in settings
 ```
 2024-11-05 10:16:51.254 [error] Error: command failed with error code 2: error parsing glob '**/${ext/**/*.{feature,yml,json}': nested alternate groups are not allowed
```

**Comment by ivangsa** [comment]
Ok, I see...
the run button on the feature only shows for files that matches the globFilter, try using 

```
"karateIDE.tests.globFilter": "**/src/e2e-test/**/*.feature"
```
or if it does not work just: `**/src/**/*.feature`

The button at the status bar runs the last execution, so if there is no last execution it doesn't work

**Comment by ivangsa** [comment]
```
2024-11-05 10:16:51.254 [error] Error: command failed with error code 2: error parsing glob '**/${ext/**/*.{feature,yml,json}': nested alternate groups are not allowed
```
which command are you preforming when showing this? bc I'm not sure is related to karate-ide extension

**Comment by gba-foundever** [comment]
> Ok, I see... the run button on the feature only shows for files that matches the globFilter, try using
> 
> ```
> "karateIDE.tests.globFilter": "**/src/e2e-test/**/*.feature"
> ```
> 
> or if it does not work just: `**/src/**/*.feature`
> 
> The button at the status bar runs the last execution, so if there is no last execution it doesn't work

Agree but it shouldn't crash at least (maybe a little user feedback but not mandaoty)

**Comment by gba-foundever** [comment]
> ```
> 2024-11-05 10:16:51.254 [error] Error: command failed with error code 2: error parsing glob '**/${ext/**/*.{feature,yml,json}': nested alternate groups are not allowed
> ```
> 
> which command are you preforming when showing this? bc I'm not sure is related to karate-ide extension

Just at open of vscode. But it's maybe due to another plugin I got. It's just that I saw a .feature inside and as I was investigating on my issue...
